region = "ap-northeast-2"
profile = "playground"
cluster_name = "EntBilling-sandbox-eks"
cluster_version = "1.22"
jx_git_url = "git@github.com:mario-hh/platform-jx3-eks-asm.git"
jx_bot_username = "jx-bot"
jx_bot_token = "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"